project:
  type: website
  output-dir: docs

website:
  title: "Liv Rosenthal's Website!"
  navbar:
    right: 
      - text: "Data Viz"
        menu: 
         - text: "Pixar Movies"
           href: TidyTuesday.html
         